export type DashboardSection =
  | "schoolYear"
  | "classes"
  | "children"
  | "myClass"
  | "subjects"
  | "notification"
  | "teachers"
  | "payment"
  | "eleves"
  | "charts"
  | "infos"
  | "notifications"
  | "myProfile"
  | "rib";
